version: '3.8'

services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8586:8586"
    env_file: .env
    depends_on:
      - products_db
    networks:
      - backend

  products_db:
    image: postgres:15
    container_name: products_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge
